#
# BlankVM/Makefile
#
# This file is part of the tinyVM source code.
# Copyright 2023 Patrick Melo <patrick@patrickmelo.com.br>
#

# Common Variables

SOURCE_DIRECTORY	= $(shell pwd)
CORE_DIRECTORY		= $(shell dirname $(SOURCE_DIRECTORY))/Source
BINARY_PATH			= $(shell dirname $(SOURCE_DIRECTORY))/BlankVM

# Core Makefile

include $(CORE_DIRECTORY)/Makefile
